name: Example pipeline
on:
 push:
   branches: 
     - master
     - develop
 pull_request:
   branches: 
     - master
     - develop
jobs:
 deployments:
   runs-on: ubuntu-latest
   environment: ${{ needs.build.outputs.env_name }}
   steps:
     - name: Checkout source php code
       uses: actions/checkout@v2
    ## Need to install zip
     - name: Instalar zip package
       run: |
         echo "Running on branch ${{ github.ref }}"
         if [ "${{ github.ref }}" = "refs/heads/master" ]; then
           echo "::set-output name=env_name::prod"
         elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
           echo "::set-output name=env_name::develop"
         else
           echo "::set-output name=env_name::qa"
         fi      

    ## Crear el ZIP file
     - name: Use variable setup in previous step
       run: echo "I'm using variable ${{ steps.branch_check.outputs.env_name }}"
     #run: tar czf deploy.tar.gz * --exclude=./deploy.tar.gz

   #- name: push to S3
   #  run: aws s3 cp deploy-${{ github.sha }}.zip s3://${{env.AWS_BUCKET_NAME}}/ --profile develop

   #- name: Create new ElasticBeanstalk Application Version
     #run: aws elasticbeanstalk create-application-version --application-name ${{envAPPLICATION_NAME}} --source-bundle S3Bucket=${{env.AWS_BUCKET_NAME}},S3Key=deploy-${{ github.sha }}.zip --version-label v-${{ github.sha }} --description testv1 --profile develop --region ${{env.AWS_DEFAULT_REGION}}
    
   #- name: Deploy new App Version
     #run: aws elasticbeanstalk update-environment --application-name ${{envAPPLICATION_NAME}} --environment-name tutorials-env --version-label v-${{ github.sha }} --profile develop --region ${{env.AWS_DEFAULT_REGION}}